### ISSUE TITLE
Manifest Version

### ISSUE THREAD

**Issue by sakai78** [arpandaze/tms-captcha#7]
THe manifest version on which this project is built is 2,which google has deprecated in 2023

OS - Windows 11 Pro (22621.1105)
Chrome Version - 109.0.5414.120 (latest)

getting an error while importing this into chrome : 

![image](https://user-images.githubusercontent.com/78425139/215963638-2a2e02f9-79bf-4aeb-a5b1-96fb8477ec25.png)

**Comment by arpandaze** [comment]
I have switched to manifest version 3 in the new release. This should be fixed now!
